/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import dynamic from "next/dynamic"
export const InstallAppButtonMap = {
"exchange2013calendar": dynamic(() => import("./exchange2013calendar/components/InstallAppButton")),
"exchange2016calendar": dynamic(() => import("./exchange2016calendar/components/InstallAppButton")),
"office365video": dynamic(() => import("./office365video/components/InstallAppButton")),
"vital": dynamic(() => import("./vital/components/InstallAppButton")),
};
export const AppSettingsComponentsMap = {
"general-app-settings": dynamic(() => import("./templates/general-app-settings/components/AppSettingsInterface")),
"zapier": dynamic(() => import("./zapier/components/AppSettingsInterface")),
};
export const EventTypeAddonMap = {
"alby": dynamic(() => import("./alby/components/EventTypeAppCardInterface")),
"btcpayserver": dynamic(() => import("./btcpayserver/components/EventTypeAppCardInterface")),
"giphy": dynamic(() => import("./giphy/components/EventTypeAppCardInterface")),
"hitpay": dynamic(() => import("./hitpay/components/EventTypeAppCardInterface")),
"hubspot": dynamic(() => import("./hubspot/components/EventTypeAppCardInterface")),
"paypal": dynamic(() => import("./paypal/components/EventTypeAppCardInterface")),
"salesforce": dynamic(() => import("./salesforce/components/EventTypeAppCardInterface")),
"stripepayment": dynamic(() => import("./stripepayment/components/EventTypeAppCardInterface")),
"booking-pages-tag": dynamic(() => import("./templates/booking-pages-tag/components/EventTypeAppCardInterface")),
"event-type-app-card": dynamic(() => import("./templates/event-type-app-card/components/EventTypeAppCardInterface")),
};
export const EventTypeSettingsMap = {
"alby": dynamic(() => import("./alby/components/EventTypeAppSettingsInterface")),
"btcpayserver": dynamic(() => import("./btcpayserver/components/EventTypeAppSettingsInterface")),
"giphy": dynamic(() => import("./giphy/components/EventTypeAppSettingsInterface")),
"hitpay": dynamic(() => import("./hitpay/components/EventTypeAppSettingsInterface")),
"paypal": dynamic(() => import("./paypal/components/EventTypeAppSettingsInterface")),
"stripepayment": dynamic(() => import("./stripepayment/components/EventTypeAppSettingsInterface")),
};