/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const apiHandlers = {
"alby": import("./alby/api"),
"applecalendar": import("./applecalendar/api"),
"btcpayserver": import("./btcpayserver/api"),
"caldavcalendar": import("./caldavcalendar/api"),
"exchange2013calendar": import("./exchange2013calendar/api"),
"exchange2016calendar": import("./exchange2016calendar/api"),
"exchangecalendar": import("./exchangecalendar/api"),
"googlecalendar": import("./googlecalendar/api"),
"googlevideo": import("./googlevideo/api"),
"hitpay": import("./hitpay/api"),
"huddle01video": import("./huddle01video/api"),
"make": import("./make/api"),
"office365calendar": import("./office365calendar/api"),
"office365video": import("./office365video/api"),
"paypal": import("./paypal/api"),
"salesforce": import("./salesforce/api"),
"stripepayment": import("./stripepayment/api"),
"basic": import("./templates/basic/api"),
"booking-pages-tag": import("./templates/booking-pages-tag/api"),
"event-type-app-card": import("./templates/event-type-app-card/api"),
"event-type-location-video-static": import("./templates/event-type-location-video-static/api"),
"general-app-settings": import("./templates/general-app-settings/api"),
"zapier": import("./zapier/api"),
"zoomvideo": import("./zoomvideo/api"),
};