/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const CrmServiceMap = {
  hubspot: import("./hubspot/lib/CrmService"),
  salesforce: import("./salesforce/lib/CrmService"),
};
